### ISSUE TITLE
Implement Proof-of-Reserves (PoR) System for Exchange Asset Verification

### ISSUE THREAD

**Issue by ijonas** [stackingturtles/omikuji#31]
## Overview

Extend Omikuji to provide comprehensive Proof-of-Reserves (PoR) capabilities, enabling cryptographic verification that custodians (exchanges, protocols, institutions) hold sufficient assets to back their liabilities. This system will leverage multiple independent Omikuji observers to create a decentralized, trustless verification network.

## Background

A Proof-of-Reserves system must provide:
- **Asset Verification**: Cryptographic proof of on-chain asset ownership
- **Liability Assessment**: Aggregated customer balances with privacy preservation
- **Cryptographic Commitments**: Individual verification without exposing user data
- **Third-Party Auditing**: Independent verification capabilities
- **Real-Time Monitoring**: Continuous reserve ratio tracking
- **Transparency**: Public dashboards with appropriate privacy protections

## System Architecture

```
┌─────────────────────────────────────────────────────────────┐
│                    PoR Ecosystem                              │
├─────────────────────────────────────────────────────────────┤
│                                                               │
│  ┌──────────────┐  ┌──────────────┐  ┌──────────────┐       │
│  │  Omikuji #1  │  │  Omikuji #2  │  │  Omikuji #3  │       │
│  │  (Observer)  │  │  (Observer)  │  │  (Observer)  │       │
│  └──────┬───────┘  └──────┬───────┘  └──────┬───────┘       │
│         │                  │                  │               │
│         ▼                  ▼                  ▼               │
│  ┌────────────────────────────────────────────────────┐      │
│  │           PoR Aggregation Smart Contract           │      │
│  │  - Consensus on observations                       │      │
│  │  - Merkle root storage                            │      │
│  │  - Timestamp & attestations                       │      │
│  └────────────────┬───────────────────────────────────┘      │
│                   │                                           │
│         ┌─────────┴──────────┬─────────────────┐            │
│         ▼                    ▼                 ▼            │
│  ┌──────────────┐  ┌──────────────┐  ┌──────────────┐      │
│  │  PostgreSQL  │  │   IPFS/AR   │  │    PoR GUI   │      │
│  │  (Detailed)  │  │  (Proofs)   │  │  (Dashboard)  │      │
│  └──────────────┘  └──────────────┘  └──────────────┘      │
└─────────────────────────────────────────────────────────────┘
```

### 1. Asset Verification Module

Implements multiple verification methods:
- **Message Signing**: For Bitcoin, Ethereum, and other chains
- **API Attestations**: Exchange-provided cryptographic proofs
- **Smart Contract Queries**: For DeFi protocols and on-chain reserves
- **Multi-signature Verification**: For cold storage validations

```rust
pub trait AssetVerifier {
    async fn verify_ownership(&self, address: &str) -> Result<AssetProof>;
    async fn get_balance(&self, address: &str) -> Result<Balance>;
    fn supported_assets(&self) -> Vec<Asset>;
}

pub struct AssetProof {
    pub asset: String,
    pub address: String,
    pub balance: U256,
    pub proof_type: ProofType,
    pub signature: Option<Vec<u8>>,
    pub timestamp: u64,
    pub block_height: u64,
}
```

### 2. Liability Tracking System

Privacy-preserving liability aggregation:
- **Merkle Tree Construction**: Efficient proof generation
- **Zero-Knowledge Proofs**: Optional enhanced privacy
- **Snapshot Management**: Point-in-time liability records

```rust
pub struct LiabilitySnapshot {
    pub timestamp: u64,
    pub merkle_root: H256,
    pub total_liabilities: HashMap<String, U256>,
    pub user_count: u64,
    pub snapshot_hash: H256,
    pub exchange_signature: Vec<u8>,
}

pub struct UserInclusionProof {
    pub user_id_hash: H256,
    pub balances: HashMap<String, U256>,
    pub merkle_proof: Vec<H256>,
    pub root: H256,
}
```

### 3. Multi-Observer Consensus

Decentralized verification through multiple Omikuji instances:

```solidity
contract ProofOfReservesAggregator {
    struct Observation {
        address observer;
        bytes32 assetProofHash;
        bytes32 liabilityRoot;
        uint256 timestamp;
        bytes signature;
    }
    
    struct ConsensusRound {
        mapping(address => Observation) observations;
        uint256 observerCount;
        bool finalized;
        bytes32 finalAssetProof;
        bytes32 finalLiabilityRoot;
    }
    
    mapping(uint256 => ConsensusRound) public rounds;
    mapping(address => bool) public authorizedObservers;
    
    uint256 public constant CONSENSUS_THRESHOLD = 67; // 67%
    uint256 public constant OBSERVATION_WINDOW = 300; // 5 minutes
    
    event ConsensusReached(
        uint256 indexed round,
        bytes32 assetProofHash,
        bytes32 liabilityRoot,
        uint256 observerCount
    );
}
```

### 4. Hybrid Storage Strategy

**On-Chain Storage**:
- Merkle roots of liability snapshots
- Consensus results from observers
- Critical timestamps and attestations
- Immutable audit trail

**PostgreSQL Database**:
```sql
-- Core tables for PoR system
CREATE TABLE asset_proofs (
    id SERIAL PRIMARY KEY,
    exchange VARCHAR(50) NOT NULL,
    asset VARCHAR(10) NOT NULL,
    address VARCHAR(255) NOT NULL,
    balance NUMERIC(78, 0) NOT NULL,
    proof_type VARCHAR(50) NOT NULL,
    proof_data JSONB,
    signature TEXT,
    observer_address VARCHAR(42) NOT NULL,
    consensus_round BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_exchange_asset_time (exchange, asset, created_at DESC)
);

CREATE TABLE liability_snapshots (
    id SERIAL PRIMARY KEY,
    exchange VARCHAR(50) NOT NULL,
    merkle_root VARCHAR(66) NOT NULL,
    total_users INTEGER NOT NULL,
    liabilities JSONB NOT NULL,
    snapshot_data_hash VARCHAR(66),
    ipfs_hash VARCHAR(100),
    observer_address VARCHAR(42) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_inclusion_proofs (
    id SERIAL PRIMARY KEY,
    snapshot_id INTEGER REFERENCES liability_snapshots(id),
    user_hash VARCHAR(66) NOT NULL,
    merkle_proof JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_snapshot (user_hash, snapshot_id)
);

CREATE TABLE consensus_records (
    id SERIAL PRIMARY KEY,
    round_id BIGINT NOT NULL,
    asset_proof_hash VARCHAR(66) NOT NULL,
    liability_root VARCHAR(66) NOT NULL,
    observer_count INTEGER NOT NULL,
    consensus_reached BOOLEAN NOT NULL,
    on_chain_tx VARCHAR(66),
    finalized_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

**IPFS/Arweave Storage**:
- Complete proof documents
- Detailed attestations
- Historical snapshots
- Audit reports

### 5. PoR Dashboard

**Core Features**:
- **Real-time Monitoring**: Live reserve ratios and health status
- **Historical Analysis**: Trends, charts, and patterns
- **Proof Verification**: Tool for users to verify inclusion
- **Multi-Exchange View**: Aggregated reserves across platforms
- **Alert System**: Notifications for threshold violations
- **API Access**: RESTful and GraphQL endpoints

**Technical Implementation**:
```typescript
// Frontend stack
- Next.js 14 with App Router
- Web3 integration (wagmi/viem)
- Real-time updates (WebSocket/SSE)
- Responsive charts (Recharts/D3)

// Backend API
- Rust REST API
- GraphQL subscriptions
- WebSocket server
- Caching layer (Redis)
```

## Configuration

```yaml
# config.yaml extensions
proof_of_reserves:
  enabled: true
  role: "observer"  # "observer" | "aggregator" | "both"
  
  # Asset verification settings
  verification:
    exchanges:
      - name: "binance"
        assets:
          btc:
            cold_wallets: ["bc1q...", "3..."]
            verification_method: "message_signing"
          eth:
            addresses: ["0x..."]
            include_layer2: true
        api:
          endpoint: "https://api.binance.com/por/v1"
          auth_method: "api_key"
      
      - name: "coinbase"
        attestation_api: "https://api.coinbase.com/v2/attestations"
        supported_assets: ["BTC", "ETH", "USDC"]
    
    defi_protocols:
      - name: "compound"
        contracts:
          ethereum: "0x..."
          base: "0x..."
        
  # Consensus configuration
  consensus:
    min_observers: 3
    threshold_percentage: 67
    observation_window: 300  # seconds
    dispute_period: 3600     # seconds
    
  # Multi-observer setup
  observers:
    - name: "omikuji-us-east"
      address: "0x..."
      endpoint: "https://us-east.omikuji.io"
      weight: 1
    - name: "omikuji-eu-west"
      address: "0x..."
      endpoint: "https://eu-west.omikuji.io"
      weight: 1
    - name: "omikuji-asia-pac"
      address: "0x..."
      endpoint: "https://asia-pac.omikuji.io"
      weight: 1
  
  # Storage configuration
  storage:
    blockchain:
      enabled: true
      networks:
        - name: "ethereum"
          aggregator_contract: "0x..."
          gas_limit: 500000
        - name: "base"
          aggregator_contract: "0x..."
          gas_limit: 300000
    
    database:
      retention_days: 365
      archive_to_s3: true
      s3_bucket: "omikuji-por-archive"
    
    ipfs:
      enabled: true
      providers:
        - "https://ipfs.io"
        - "https://cloudflare-ipfs.com"
      pinning_service: "pinata"
    
  # Dashboard configuration
  dashboard:
    enabled: true
    port: 8081
    cors_origins: ["https://app.omikuji.io"]
    rate_limiting:
      enabled: true
      requests_per_minute: 60
    features:
      public_api: true
      user_verification: true
      historical_data: true
      export_reports: true
```

### Phase 1: Core Infrastructure (Weeks 1-4)
- [ ] Asset verification module with BTC/ETH support
- [ ] Basic liability tracking with merkle trees
- [ ] Database schema and migrations
- [ ] Simple consensus mechanism
- [ ] MVP dashboard

### Phase 2: Multi-Observer System (Weeks 5-8)
- [ ] P2P communication between observers
- [ ] Smart contract for consensus
- [ ] Byzantine fault tolerance
- [ ] Enhanced dashboard features
- [ ] IPFS integration

### Phase 3: Exchange Integration (Weeks 9-12)
- [ ] Binance PoR API integration
- [ ] Coinbase attestation support
- [ ] Kraken proof system
- [ ] Generic exchange adapter framework
- [ ] DeFi protocol support

### Phase 4: Production Features (Weeks 13-16)
- [ ] Zero-knowledge proof options
- [ ] Advanced analytics dashboard
- [ ] Automated alerting system
- [ ] Comprehensive API documentation
- [ ] Security audit

## Security Considerations

1. **Observer Authentication**: Cryptographic identity for each instance
2. **Proof Integrity**: Multiple signatures and consensus requirements
3. **Privacy Protection**: User data never exposed, only commitments
4. **Tamper Resistance**: Blockchain immutability for historical records
5. **Rate Limiting**: Protection against spam and DoS
6. **Key Management**: Secure storage of signing keys (#25-27)

## Success Metrics

- [ ] Support for top 10 exchanges by volume
- [ ] < 1% false positive rate in consensus
- [ ] < 5 minute end-to-end verification time
- [ ] 99.9% uptime for dashboard
- [ ] > 1000 concurrent proof verifications/second
- [ ] Complete audit trail for 365 days

## Future Enhancements

1. **Cross-Chain Reserves**: Unified view across all chains
2. **Regulatory Compliance**: Built-in reporting for regulators
3. **Mobile Apps**: iOS/Android proof verification
4. **Hardware Security**: HSM integration for signing
5. **Decentralized Dashboard**: IPFS-hosted frontend

## Dependencies

- #25-27: Secure key management for observer signing
- #28: Enhanced metrics for PoR monitoring
- #29: USD valuation of reserves
- #30: MCP interface for AI-driven analysis

## References

- [Binance Proof of Reserves](https://www.binance.com/en/proof-of-reserves)
- [Kraken Proof of Reserves](https://www.kraken.com/proof-of-reserves)
- [Nic Carter's PoR Framework](https://niccarter.info/proof-of-reserves/)
- [Merkle Tree Constructions](https://en.wikipedia.org/wiki/Merkle_tree)

This implementation will position Omikuji as critical infrastructure for the cryptocurrency ecosystem, providing trustless verification of custodial reserves and enhancing transparency across the industry.
