### ISSUE TITLE
CLI Environment Management

### ISSUE THREAD

**Issue by ijonas** [stackingturtles/omikuji#41]
## Overview
Implement environment-specific configuration management to support different deployment scenarios (development, staging, production).

**Parent Issue**: #32

### 1. Environment-Specific Configurations
Manage multiple environments with ease:

```bash
# List available environments
omikuji env list

# Show current environment
omikuji env current

# Switch environment
omikuji env use production
omikuji env use development

# Create new environment
omikuji env create staging --from production
```

### 2. Environment Configuration Structure
Organize configs by environment:

```
.omikuji/
├── environments/
│   ├── development/
│   │   └── config.yaml
│   ├── staging/
│   │   └── config.yaml
│   └── production/
│       └── config.yaml
└── current-env  # Symlink to active environment
```

### 3. Environment Variables Integration
Per-environment variable management:

```bash
# Set environment-specific variables
omikuji env set development NETWORK_RPC_URL=http://localhost:8545
omikuji env set production NETWORK_RPC_URL=https://eth.llamarpc.com

# List environment variables
omikuji env vars

# Export environment variables
omikuji env export > .env.production
```

### 4. Environment Inheritance
Base configurations with overrides:

```yaml
# base.yaml
networks:
  - name: ethereum
    transaction_type: eip1559
    
datafeeds:
  - name: eth_usd
    contract_type: fluxmon
    check_frequency: 60

# production.yaml (inherits from base)
extends: base.yaml
networks:
  - name: ethereum
    rpc_url: https://eth.llamarpc.com  # Override
    
datafeeds:
  - name: eth_usd
    deviation_threshold_pct: 0.5  # Override
```

### 5. Environment Comparison
Compare configurations across environments:

```bash
# Compare two environments
omikuji env diff development production

# Compare specific sections
omikuji env diff development staging --section feeds

# Output:
# Development vs Production:
# - networks.ethereum.rpc_url: 
#   < http://localhost:8545
#   > https://eth.llamarpc.com
# - datafeeds.eth_usd.deviation_threshold_pct:
#   < 2.0
#   > 0.5
```

### 6. Safe Environment Switching
Prevent accidental production changes:

```bash
# Protection for production
omikuji env use production --confirm

# Lock environment to prevent changes
omikuji env lock production

# Unlock with confirmation
omikuji env unlock production --confirm
```

### Configuration Priority
1. Command-line arguments
2. Environment variables
3. Environment-specific config
4. Base configuration
5. Default values

### Environment Metadata
```yaml
# .omikuji/environments/production/metadata.yaml
name: production
created_at: 2024-01-15T10:00:00Z
locked: true
description: Production environment - mainnet
extends: base
variables:
  NETWORK_RPC_URL: https://eth.llamarpc.com
  LOG_LEVEL: info
```

### Commands Structure
```
omikuji env
├── list
├── current
├── use <environment> [--confirm]
├── create <name> [--from <source>]
├── delete <name> [--confirm]
├── set <environment> <key>=<value>
├── vars [<environment>]
├── export [<environment>]
├── diff <env1> <env2> [--section <section>]
├── lock <environment>
└── unlock <environment> --confirm
```

## Dependencies
- `dotenv` for environment variable handling
- `similar` for diff generation

## Success Criteria
1. Easy switching between environments
2. Clear separation of configuration concerns
3. Protection against accidental production changes
4. Inheritance to reduce duplication
5. Clear visibility of environment differences
