### ISSUE TITLE
CLI Advanced Features

### ISSUE THREAD

**Issue by ijonas** [stackingturtles/omikuji#42]
## Overview
Implement advanced configuration features including multi-file support, hot reload capabilities, and sensitive data encryption.

**Parent Issue**: #32

### 1. Multi-File Configuration Support
Split configurations across multiple files:

```bash
# Load configuration from directory
omikuji run --config-dir ./config/

# Merge multiple config files
omikuji run --config base.yaml --config overrides.yaml

# Show merged configuration
omikuji config show --merged
```

**Directory Structure:**
```
config/
├── 00-networks.yaml      # Networks configuration
├── 10-feeds-crypto.yaml  # Crypto price feeds
├── 20-feeds-forex.yaml   # Forex feeds
└── 99-overrides.yaml     # Environment overrides
```

**Merge Rules:**
- Files processed in alphabetical order
- Later files override earlier ones
- Arrays are merged, not replaced
- Deep merge for nested objects

### 2. Hot Reload Functionality
Automatically reload configuration changes:

```bash
# Enable hot reload
omikuji run --hot-reload

# Watch specific files
omikuji run --watch config.yaml --watch feeds/*.yaml

# Reload notifications
# [INFO] Configuration changed: config.yaml
# [INFO] Reloading feeds: eth_usd, btc_usd
# [INFO] Reload complete
```

**Hot Reload Features:**
- File system watching
- Graceful reload without interruption
- Validation before applying changes
- Rollback on invalid configuration
- Reload hooks for custom actions

### 3. Sensitive Data Encryption
Protect sensitive configuration data:

```bash
# Encrypt sensitive values
omikuji config encrypt --key mypassword

# Decrypt for viewing
omikuji config decrypt --key mypassword

# Run with encrypted config
omikuji run --decrypt-key mypassword
```

**Encryption Scope:**
```yaml
networks:
  - name: ethereum
    rpc_url: \!encrypted "U2FsdGVkX1+..."  # Encrypted value
    
# Private keys always encrypted
private_key: \!encrypted "U2FsdGVkX1+..."

# API keys encrypted
datafeeds:
  - name: premium_feed
    feed_url: https://api.example.com
    api_key: \!encrypted "U2FsdGVkX1+..."
```

### 4. Configuration Includes
Include external configuration files:

```yaml
# main.yaml
\!include networks/ethereum.yaml
\!include networks/polygon.yaml

datafeeds:
  \!include feeds/crypto/*.yaml
  \!include feeds/forex/*.yaml
```

### 5. Dynamic Configuration
Support for dynamic values:

```yaml
datafeeds:
  - name: eth_usd
    # Dynamic URL based on environment
    feed_url: \!env FEED_API_URL
    
    # Computed values
    check_frequency: \!expr "60 if env.ENVIRONMENT == 'production' else 10"
    
    # Reference other config values
    contract_address: \!ref contracts.eth_usd.address
```

### File Watching Implementation
```rust
use notify::{Watcher, RecursiveMode, watcher};

// Watch for changes
let (tx, rx) = channel();
let mut watcher = watcher(tx, Duration::from_secs(2))?;
watcher.watch("config.yaml", RecursiveMode::NonRecursive)?;
```

### Encryption Standards
- Algorithm: AES-256-GCM
- Key derivation: PBKDF2
- Salt stored with encrypted data
- Support for external key management

### Configuration Processing Pipeline
1. Load all configuration files
2. Process includes
3. Evaluate dynamic values
4. Decrypt sensitive data
5. Merge configurations
6. Validate final result

### Reload Safety
- Maintain previous valid config
- Test new config in isolation
- Atomic swap on success
- Automatic rollback on failure
- No feed interruption during reload

## Dependencies
- `notify` for file watching
- `aes-gcm` for encryption
- `include_dir` for includes
- `eval` or custom expression parser

## Success Criteria
1. Modular configuration management
2. Zero-downtime configuration updates
3. Secure handling of sensitive data
4. Flexible configuration composition
5. Reliable hot reload without data loss
