### ISSUE TITLE
Implement EIP-7702 Support for Enhanced Wallet and Gas Management

### ISSUE THREAD

**Issue by ijonas** [stackingturtles/omikuji#47]
## Overview

Implement support for EIP-7702 to enhance Omikuji's wallet management, gas budget controls, and security model. EIP-7702 allows EOAs (Externally Owned Accounts) to temporarily delegate to smart contract code, enabling sophisticated control mechanisms without permanent account transformation.

## Background

EIP-7702 introduces a new transaction type that allows EOAs to "borrow" code from a smart contract while maintaining their own state. This provides smart contract-like functionality to regular wallets, opening new possibilities for:
- Granular permission systems
- On-chain budget enforcement
- Secure sub-key delegation
- Gas sponsorship patterns

### 1. Feed Management Contract

Create a smart contract that EOAs can delegate to for enhanced feed management:

```solidity
contract OmikujiFeedManager {
    // Per-feed gas budgets
    mapping(address => uint256) feedGasBudgets;
    // Daily spending limits
    mapping(uint256 => uint256) dailySpent;
    // Authorized operators with specific permissions
    mapping(address => uint256) operatorPermissions;
    
    // Permission flags
    uint256 constant PERM_UPDATE_FEED = 1;
    uint256 constant PERM_MODIFY_PARAMS = 2;
    uint256 constant PERM_EMERGENCY_PAUSE = 4;
}
```

### 2. Enhanced Wallet Architecture

Transform Omikuji's wallet management to support:
- **Per-feed wallets**: Each feed gets its own EOA with delegated controls
- **Sub-key system**: Issue limited-permission keys for different operations
- **Gas budget enforcement**: On-chain limits prevent overspending
- **Dynamic delegation**: Adjust permissions without key rotation

### 3. Configuration Enhancement

Extend the YAML configuration to support EIP-7702 features:

```yaml
datafeeds:
  - name: eth_usd
    wallet_config:
      type: eip7702_delegated
      delegate_to: "0xOmikujiFeedManager"
      permissions:
        - update_feed
        - read_state
      gas_budget:
        daily_limit_gwei: 1000000
        per_update_limit: 50000
      sub_keys:
        - address: "0xOperator1"
          permissions: ["update_feed"]
          rate_limit: "10/hour"
        - address: "0xAIAgent1"
          permissions: ["update_feed"]
          rate_limit: "5/hour"
          max_deviation: 2.0  # Can only update if deviation > 2%
```

### 4. Integration Benefits

**Security (Addresses #24-27)**:
- Private keys become less critical - they only set delegations
- Compromised sub-keys have limited damage potential
- Temporary delegations can be revoked

**AI/MCP Integration (Enhances #30)**:
- AI agents receive sub-keys with strict permissions
- No need for expensive smart wallet deployments
- Built-in rate limiting and budget controls

**Gas Management (Improves #29, #36)**:
- On-chain enforcement of gas budgets
- Per-feed, per-day, per-transaction limits
- Programmable gas optimization strategies

### Phase 1: Core Infrastructure (Weeks 1-2)
- [ ] Design and deploy OmikujiFeedManager contract
- [ ] Update wallet module to support EIP-7702 transactions
- [ ] Implement delegation management utilities

### Phase 2: Feed Integration (Weeks 3-4)
- [ ] Extend configuration parser for new wallet options
- [ ] Implement per-feed wallet creation
- [ ] Add delegation lifecycle management
- [ ] Create sub-key generation and management

### Phase 3: Budget Controls (Weeks 5-6)
- [ ] Implement on-chain gas budget tracking
- [ ] Add budget monitoring and alerts
- [ ] Create budget adjustment mechanisms
- [ ] Integrate with existing metrics (#28)

### Phase 4: Advanced Features (Weeks 7-8)
- [ ] AI agent sub-key issuance system
- [ ] Permission-based MCP endpoints
- [ ] Delegation audit logging
- [ ] Multi-network delegation strategies

## Success Criteria

1. **Security**: Reduced private key exposure with granular permissions
2. **Flexibility**: Dynamic permission management without key rotation
3. **Cost Control**: Enforced on-chain gas budgets
4. **Scalability**: Efficient multi-feed, multi-network management
5. **AI-Ready**: Safe integration with autonomous agents

## Dependencies

- Migration to alloy-rs (#34) should be completed first for better EIP-7702 support
- Builds upon secure key management (#24-27)
- Enhances MCP server implementation (#30)

## References

- [EIP-7702 Specification](https://eips.ethereum.org/EIPS/eip-7702)
- [Tenderly Blog: How EIP-7702 Gives EOAs Smart Contract Functionalities](https://blog.tenderly.co/how-eip-7702-gives-eoas-smart-contract-functionalities/)

## Impact

This implementation would position Omikuji at the forefront of oracle security and automation, leveraging cutting-edge Ethereum features to solve real-world challenges in decentralized data feed management.
