### ISSUE TITLE
Implement test coverage tracking with Codecov integration

### ISSUE THREAD

**Issue by ijonas** [stackingturtles/omikuji#52]
## Overview

Implement comprehensive test coverage tracking for the Omikuji project to monitor code quality over time and across releases.

## Motivation

- Currently no visibility into test coverage percentage
- No way to track coverage trends over time
- No automated checks to prevent coverage regression
- Industry best practices recommend 70-80% minimum coverage

### 1. Add Coverage Generation to CI/CD

Update `.github/workflows/ci.yml` with a dedicated coverage job:

```yaml
coverage:
  name: Code Coverage
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
      
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
      
    - name: Generate coverage
      run: cargo tarpaulin --out Xml --verbose
      
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./cobertura.xml
        fail_ci_if_error: true
```

### 2. Codecov Integration

- Sign up for Codecov (free for open source)
- Add repository to Codecov dashboard
- Add coverage badge to README.md
- Create `codecov.yml` configuration:

```yaml
coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 80%
        
ignore:
  - "src/*/tests.rs"
  - "tests/**"
  - "examples/**"
```

### 3. Local Coverage Support

Add to Makefile:

```makefile
# Generate HTML coverage report locally
coverage:
	cargo tarpaulin --out Html
	open tarpaulin-report.html

# Generate XML coverage for CI
coverage-ci:
	cargo tarpaulin --out Xml
```

### 4. Tarpaulin Configuration

Create `.tarpaulinrc` file:

```toml
[default]
exclude-files = ["*/tests.rs", "tests/*"]
timeout = "600"
```

### 5. Documentation Updates

- Add coverage badge to README.md
- Document how to run coverage locally
- Add coverage requirements to contributing guidelines

## Benefits

- **Visibility**: Coverage percentage always visible via badge
- **Historical Tracking**: Coverage trends over commits and releases
- **PR Protection**: Automatic checks prevent coverage drops
- **Quality Metrics**: Data-driven approach to code quality
- **Developer Awareness**: Clear coverage goals and feedback

## Implementation Steps

1. [ ] Set up Codecov account and add repository
2. [ ] Update CI workflow with coverage job
3. [ ] Add codecov.yml configuration
4. [ ] Update Makefile with coverage commands
5. [ ] Add .tarpaulinrc configuration
6. [ ] Update README with badge and documentation
7. [ ] Test coverage generation locally and in CI

## Success Criteria

- Coverage reports generated on every PR and push to main
- Coverage badge visible in README
- Historical coverage data available in Codecov dashboard
- PR comments show coverage changes
- Local coverage generation works with `make coverage`

## Alternative Considerations

- **grcov**: More complex setup but potentially more accurate
- **Coveralls**: Alternative to Codecov, also free for open source
- **llvm-cov**: Built-in Rust coverage, still experimental

## References

- [cargo-tarpaulin](https://github.com/xd009642/tarpaulin)
- [Codecov Rust documentation](https://about.codecov.io/language/rust/)
- [Rust Coverage Guidelines](https://doc.rust-lang.org/rustc/instrument-coverage.html)
