### ISSUE TITLE
Implement Blockchain Event Monitoring with Webhook Integration

### ISSUE THREAD

**Issue by ijonas** [stackingturtles/omikuji#61]
## Overview

Omikuji currently monitors external APIs and updates blockchain contracts based on data changes. This issue proposes extending Omikuji to monitor blockchain events and trigger webhooks, enabling bidirectional communication between on-chain and off-chain systems.

The feature will allow Omikuji to:
1. Monitor specific events emitted by smart contracts
2. Call configured webhooks with event data as payload
3. Process webhook responses that contain ABI-encoded contract calls
4. Execute the returned contract calls on-chain

This creates a powerful feedback loop where blockchain events can trigger off-chain computations that result in new on-chain actions.

### 1. Event Monitoring Configuration

Configure contracts and events to monitor:

```yaml
event_monitors:
  - name: "price_request_monitor"
    network: "ethereum-mainnet"
    contract_address: "0x1234567890123456789012345678901234567890"
    event_signature: "PriceRequested(address,bytes32,uint256)"
    webhook:
      url: "https://api.example.com/handle-price-request"
      method: "POST"
      headers:
        Authorization: "Bearer ${WEBHOOK_API_KEY}"
      timeout_seconds: 30
      retry_attempts: 3
    response_handling:
      type: "contract_call"  # or "log_only", "store_db"
      target_contract: "0xabcdef1234567890123456789012345678901234"
      max_gas_price_gwei: 100
```

### 2. Event Processing Pipeline

```mermaid
graph LR
    A[Contract Event] --> B[Event Monitor]
    B --> C[Event Parser]
    C --> D[Webhook Caller]
    D --> E[Response Handler]
    E --> F{Response Type}
    F -->|contract_call| G[ABI Decoder]
    F -->|log_only| H[Logger]
    F -->|store_db| I[Database]
    G --> J[Transaction Builder]
    J --> K[Contract Execution]
```

### 3. Webhook Payload Structure

Events will be sent to webhooks with standardized payload:

```json
{
  "monitor_name": "price_request_monitor",
  "event": {
    "name": "PriceRequested",
    "contract_address": "0x1234...",
    "transaction_hash": "0xabcd...",
    "block_number": 18500000,
    "log_index": 42,
    "removed": false,
    "topics": ["0x123...", "0x456..."],
    "data": "0x789...",
    "decoded_args": {
      "requester": "0x9876...",
      "identifier": "0x5553442d555344000000000000000000",
      "timestamp": 1700000000
    }
  },
  "context": {
    "network": "ethereum-mainnet",
    "timestamp": "2024-01-20T10:30:00Z",
    "omikuji_version": "0.4.0"
  }
}
```

### 4. Webhook Response for Contract Calls

Webhooks can return ABI-encoded contract calls:

```json
{
  "action": "contract_call",
  "calls": [
    {
      "to": "0xabcdef1234567890123456789012345678901234",
      "data": "0x4e487b71...",  // ABI-encoded function call
      "value": "0",
      "gas_limit": 200000,
      "description": "submitPrice(bytes32,uint256)"
    }
  ],
  "metadata": {
    "request_id": "req_123abc",
    "computation_time_ms": 150
  }
}
```

### 5. Error Handling and Retry Logic

```yaml
event_monitors:
  - name: "critical_event_monitor"
    # ... other config ...
    error_handling:
      webhook_timeout_action: "retry"  # or "skip", "alert"
      max_retries: 3
      retry_delay_seconds: [5, 10, 30]  # exponential backoff
      failed_webhook_action: "log_and_alert"
      invalid_response_action: "log_and_skip"
    alerts:
      on_webhook_failure: true
      on_invalid_abi: true
      alert_channels: ["pagerduty", "email"]
```

### New Module: `src/events/`

```
src/events/
├── mod.rs              # Module exports
├── monitor.rs          # Event monitoring orchestration
├── listener.rs         # Blockchain event listeners
├── parser.rs           # Event parsing and decoding
├── webhook.rs          # Webhook client
├── response_handler.rs # Response processing
├── abi_decoder.rs      # ABI decoding utilities
└── tests.rs            # Unit tests
```

### Integration Points

1. **Network Module**: Reuse existing provider connections
2. **Contract Module**: Extend with event ABI definitions
3. **Gas Module**: Utilize for response transaction pricing
4. **Metrics Module**: Add event monitoring metrics
5. **Database Module**: Store event history and webhook responses

### Concurrent Event Processing

```rust
pub struct EventMonitor {
    config: EventMonitorConfig,
    provider: Arc<Provider>,
    webhook_client: WebhookClient,
    response_handler: ResponseHandler,
}

impl EventMonitor {
    pub async fn start(&self) -> Result<()> {
        let filter = self.create_event_filter()?;
        let mut stream = self.provider.subscribe_logs(&filter).await?;
        
        while let Some(log) = stream.next().await {
            // Process events concurrently
            tokio::spawn(self.clone().process_event(log));
        }
        Ok(())
    }
    
    async fn process_event(self, log: Log) -> Result<()> {
        let event = self.parse_event(log)?;
        let webhook_response = self.call_webhook(event).await?;
        self.handle_response(webhook_response).await?;
        Ok(())
    }
}
```

### 1. Event Filtering

Support for complex event filtering:

```rust
#[derive(Debug, Clone, Deserialize)]
pub struct EventFilter {
    pub address: Address,
    pub topics: Vec<Option<H256>>,
    pub from_block: Option<BlockNumber>,
    pub to_block: Option<BlockNumber>,
}
```

### 2. ABI Decoding

Leverage existing Alloy library for ABI operations:

```rust
use alloy::sol_types::SolCall;

pub fn decode_response_call(data: &str) -> Result<DecodedCall> {
    let bytes = hex::decode(data)?;
    let selector = &bytes[0..4];
    
    match selector {
        SUBMIT_PRICE_SELECTOR => {
            let call = SubmitPriceCall::abi_decode(&bytes)?;
            Ok(DecodedCall::SubmitPrice(call))
        }
        // ... other selectors
        _ => Err(anyhow\!("Unknown function selector"))
    }
}
```

### 3. Webhook Client

Resilient HTTP client with retry logic:

```rust
pub struct WebhookClient {
    client: reqwest::Client,
    config: WebhookConfig,
}

impl WebhookClient {
    pub async fn call(&self, payload: EventPayload) -> Result<WebhookResponse> {
        let mut retries = 0;
        loop {
            match self.execute_request(&payload).await {
                Ok(response) => return Ok(response),
                Err(e) if retries < self.config.max_retries => {
                    retries += 1;
                    let delay = self.config.retry_delays[retries - 1];
                    tokio::time::sleep(Duration::from_secs(delay)).await;
                }
                Err(e) => return Err(e),
            }
        }
    }
}
```

### 4. Metrics Integration

New metrics for event monitoring:

```rust
// Event monitoring metrics
event_monitor_events_total{monitor="price_request", status="processed"}
event_monitor_webhook_calls_total{monitor="price_request", status="success"}
event_monitor_webhook_duration_seconds{monitor="price_request"}
event_monitor_contract_calls_total{monitor="price_request", status="success"}
event_monitor_errors_total{monitor="price_request", error_type="webhook_timeout"}
```

### Complete Event Monitor Configuration

```yaml
event_monitors:
  - name: "oracle_request_handler"
    enabled: true
    network: "ethereum-mainnet"
    
    # Contract and event configuration
    contract:
      address: "0x1234567890123456789012345678901234567890"
      abi_path: "./abi/OracleContract.json"  # Optional: for better decoding
    
    event:
      signature: "DataRequested(address indexed requester, bytes32 indexed identifier, uint256 timestamp, bytes ancillaryData)"
      # Or use topic hash directly
      topic0: "0xabc123..."
    
    # Filtering options
    filters:
      from_block: "latest"  # or specific block number
      confirmations: 2      # Wait for N confirmations
      
    # Webhook configuration  
    webhook:
      url: "https://api.oracle-service.com/process-request"
      method: "POST"
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer ${ORACLE_WEBHOOK_TOKEN}"
        X-Omikuji-Network: "{{ network }}"  # Template variables
      
      timeout_seconds: 30
      
      # Retry configuration
      retry:
        enabled: true
        max_attempts: 3
        delays: [5, 15, 30]
        backoff_multiplier: 2.0
    
    # Response handling
    response:
      type: "contract_call"  # contract_call | log_only | store_db | multi_action
      
      # For contract_call type
      contract_call:
        target_contract: "{{ event.contract_address }}"  # Can use templates
        max_gas_price_gwei: 150
        gas_limit_multiplier: 1.2
        value_wei: 0
        
      # Validation
      validation:
        require_signature: true
        allowed_signers: ["0xSigner1...", "0xSigner2..."]
        max_response_age_seconds: 300
    
    # Monitoring and alerts
    monitoring:
      alert_on_failure: true
      alert_channels: ["slack", "pagerduty"]
      metrics_enabled: true
      
    # Storage options
    storage:
      store_events: true
      store_responses: true
      retention_days: 30
```

## Success Criteria

1. **Reliable Event Monitoring**: Successfully capture and process 99.9% of relevant events
2. **Webhook Integration**: Support for secure, authenticated webhook calls with retry logic
3. **ABI Encoding/Decoding**: Correctly parse event data and encode response transactions
4. **Performance**: Process events within 5 seconds of emission (excluding confirmations)
5. **Error Handling**: Graceful handling of webhook failures and invalid responses
6. **Observability**: Comprehensive metrics and logging for debugging
7. **Security**: Validate webhook responses and implement signing verification
8. **Testing**: >80% test coverage for the new event monitoring module

## Dependencies

- Existing Alloy library for Ethereum interactions and ABI handling
- `tokio` for async event processing
- `reqwest` with retry middleware for webhook calls
- Existing metrics and database infrastructure

## Migration Path

1. **Phase 1**: Implement basic event monitoring without webhook responses
2. **Phase 2**: Add webhook integration with simple logging
3. **Phase 3**: Implement ABI-encoded response handling
4. **Phase 4**: Add advanced features (filtering, validation, alerts)

## Related Issues

- Could enhance #45 (CLI Monitoring Features) with event monitoring commands
- Complements existing datafeed functionality by adding bidirectional communication
- May benefit from #46 (Plugin System) for custom event processors

## How to Contribute

1. Review the architecture design and provide feedback
2. Implement individual components (event listener, webhook client, etc.)
3. Add comprehensive tests for each component
4. Update documentation with event monitoring examples
5. Test with real contracts on testnets

This feature will significantly expand Omikuji's capabilities, enabling it to serve as a bidirectional bridge between blockchain smart contracts and off-chain systems.
